#!/usr/bin/env python3
"""Generate manuscript paper_assets from frozen repository artefacts.

Does NOT invent coding results, IRR, realization rates, or gaps.
Methods/descriptive tables are filled from Phase 1–2 freezes.
Results tables/figures are scaffolded as placeholders with headers only.
"""

from __future__ import annotations

import csv
import json
import textwrap
from collections import Counter
from pathlib import Path

import yaml

REPO_ROOT = Path(__file__).resolve().parents[2]
AFF = REPO_ROOT / "localgovbench_measurement_validation" / "affordance"
ASSETS = REPO_ROOT / "paper_assets"
PILOT_DATA = (
    REPO_ROOT
    / "localgovbench_measurement_validation"
    / "pilot_public_satisfiability"
    / "data"
)


def _read_csv(path: Path) -> list[dict[str, str]]:
    with path.open(encoding="utf-8", newline="") as handle:
        return list(csv.DictReader(handle))


def _write_csv(path: Path, rows: list[dict[str, str]], fieldnames: list[str]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("w", encoding="utf-8", newline="") as handle:
        writer = csv.DictWriter(handle, fieldnames=fieldnames, lineterminator="\n")
        writer.writeheader()
        for row in rows:
            writer.writerow({k: row.get(k, "") for k in fieldnames})


def _md_table(headers: list[str], rows: list[list[str]]) -> str:
    line = "| " + " | ".join(headers) + " |"
    sep = "| " + " | ".join("---" for _ in headers) + " |"
    body = "\n".join("| " + " | ".join(r) + " |" for r in rows)
    return "\n".join([line, sep, body]) if rows else "\n".join([line, sep])


def _tex_table(
    caption: str,
    label: str,
    headers: list[str],
    rows: list[list[str]],
    notes: str = "",
) -> str:
    cols = "l" + "r" * (len(headers) - 1) if len(headers) > 1 else "l"
    # Prefer left-align for text-heavy tables
    if any(len(h) > 12 for h in headers) or (
        rows and any(len(str(c)) > 20 for c in rows[0])
    ):
        cols = "l" * len(headers)
    head = " & ".join(headers) + r" \\"
    body = "\n".join(" & ".join(_tex_escape(c) for c in r) + r" \\" for r in rows)
    note_block = f"\n\\smallskip\\noindent\\footnotesize{{{_tex_escape(notes)}}}\n" if notes else ""
    return textwrap.dedent(
        f"""\
        % Auto-generated by paper_assets/scripts/generate_all_paper_assets.py
        % Do not treat as Results unless the source artefact is a completed study output.
        \\begin{{table}}[t]
        \\centering
        \\caption{{{_tex_escape(caption)}}}
        \\label{{{label}}}
        \\begin{{tabular}}{{{cols}}}
        \\toprule
        {head}
        \\midrule
        {body}
        \\bottomrule
        \\end{{tabular}}
        {note_block}\\end{{table}}
        """
    )


def _tex_escape(s: str) -> str:
    out = str(s)
    for a, b in [
        ("\\", r"\textbackslash{}"),
        ("&", r"\&"),
        ("%", r"\%"),
        ("_", r"\_"),
        ("#", r"\#"),
        ("{", r"\{"),
        ("}", r"\}"),
    ]:
        out = out.replace(a, b)
    return out


def _write_triple(
    table_id: str,
    title: str,
    caption: str,
    label: str,
    fieldnames: list[str],
    rows: list[dict[str, str]],
    notes: str,
    status: str,
    sources: list[str],
) -> None:
    root = ASSETS / "tables" / table_id
    root.mkdir(parents=True, exist_ok=True)
    _write_csv(root / f"{table_id}.csv", rows, fieldnames)
    md_rows = [[r.get(h, "") for h in fieldnames] for r in rows]
    md = "\n".join(
        [
            f"# {table_id}: {title}",
            "",
            f"**Status:** {status}",
            "",
            f"**Caption draft:** {caption}",
            "",
            "**Source artefacts:**",
            "",
            *[f"- `{s}`" for s in sources],
            "",
            _md_table(fieldnames, md_rows),
            "",
            f"**Notes:** {notes}",
            "",
            "**Cross references:** `docs/supplements/`; `paper_assets/paper_asset_manifest.md`",
            "",
        ]
    )
    (root / f"{table_id}.md").write_text(md, encoding="utf-8")
    tex = _tex_table(caption, label, fieldnames, md_rows, notes)
    (root / f"{table_id}.tex").write_text(tex, encoding="utf-8")
    # Collect into latex/
    (ASSETS / "latex" / "tables" / f"{table_id}.tex").write_text(tex, encoding="utf-8")
    meta = {
        "table_id": table_id,
        "title": title,
        "status": status,
        "caption": caption,
        "label": label,
        "sources": sources,
        "n_rows": len(rows),
        "notes": notes,
    }
    (root / "meta.json").write_text(json.dumps(meta, indent=2) + "\n", encoding="utf-8")


def _write_figure_scaffold(
    fig_id: str,
    title: str,
    caption: str,
    status: str,
    expected_input: list[str],
    expected_output: str,
    cross_refs: list[str],
    script_name: str,
    script_body: str,
) -> None:
    root = ASSETS / "figures" / fig_id
    root.mkdir(parents=True, exist_ok=True)
    (root / "caption.md").write_text(
        "\n".join(
            [
                f"# {fig_id}: {title}",
                "",
                f"**Status:** {status}",
                "",
                "## Caption draft",
                "",
                caption,
                "",
                "## Expected input",
                "",
                *[f"- `{p}`" for p in expected_input],
                "",
                "## Expected output",
                "",
                f"- `{expected_output}`",
                "",
                "## Cross references",
                "",
                *[f"- {c}" for c in cross_refs],
                "",
                "**Non-claim:** This figure must not be read as a jurisdiction ranking, readiness score, shortfall score, or compliance verdict.",
                "",
            ]
        ),
        encoding="utf-8",
    )
    placeholder = root / "placeholder.svg"
    placeholder.write_text(
        textwrap.dedent(
            f"""\
            <?xml version="1.0" encoding="UTF-8"?>
            <svg xmlns="http://www.w3.org/2000/svg" width="800" height="450" viewBox="0 0 800 450">
              <rect width="800" height="450" fill="#f7f7f7" stroke="#333"/>
              <text x="40" y="60" font-family="Helvetica, Arial, sans-serif" font-size="22" fill="#222">{fig_id}: {title}</text>
              <text x="40" y="100" font-family="Helvetica, Arial, sans-serif" font-size="14" fill="#555">Status: {status}</text>
              <text x="40" y="140" font-family="Helvetica, Arial, sans-serif" font-size="14" fill="#555">Generate via: scripts/{script_name}</text>
              <text x="40" y="200" font-family="Helvetica, Arial, sans-serif" font-size="13" fill="#777">No invented findings. Placeholder until script succeeds.</text>
            </svg>
            """
        ),
        encoding="utf-8",
    )
    script_path = ASSETS / "scripts" / script_name
    script_path.write_text(script_body, encoding="utf-8")
    script_path.chmod(0o755)
    meta = {
        "figure_id": fig_id,
        "title": title,
        "status": status,
        "caption": caption,
        "expected_input": expected_input,
        "expected_output": expected_output,
        "script": f"paper_assets/scripts/{script_name}",
        "cross_refs": cross_refs,
    }
    (root / "meta.json").write_text(json.dumps(meta, indent=2) + "\n", encoding="utf-8")


def generate_tables() -> None:
    lock = json.loads((AFF / "locks" / "corpus_lock_v1.json").read_text(encoding="utf-8"))
    registry = _read_csv(PILOT_DATA / "source_registry_expanded.csv")
    inv = _read_csv(AFF / "outputs" / "schema_inventory_v1.csv")
    functions = yaml.safe_load((AFF / "config" / "disclosure_functions_v1.yaml").read_text())
    template = _read_csv(AFF / "coding" / "templates" / "schema_coding_template_v1.csv")
    pilot = _read_csv(AFF / "coding" / "templates" / "pilot_coding_manifest_v1.csv")
    labels_text = (AFF / "coding" / "config" / "coding_labels_v1.yaml").read_text(encoding="utf-8")
    # Parse labels carefully — file may have multiline quirks; extract list blocks via simple read of known keys
    labels = {
        "support_level": ["dedicated", "indirect", "absent"],
        "applicability_label": [
            "universal",
            "conditional",
            "jurisdiction_specific",
            "object_specific",
            "catalogue_inapplicable",
            "unknown",
        ],
        "encoding_type": ["free_text", "structured", "mixed", "other", "not_applicable"],
        "documentary_linkage_layer": [
            "generic_url",
            "record_locator",
            "function_specific",
            "none",
            "not_applicable",
        ],
    }
    # Prefer YAML if parseable for support_level block
    try:
        # Read only first enum blocks with a tolerant approach
        import re

        for key in labels:
            m = re.search(rf"{key}:\n((?:  - .+\n)+)", labels_text)
            if m:
                labels[key] = [
                    line.strip()[2:].strip() for line in m.group(1).splitlines() if line.strip().startswith("-")
                ]
    except Exception:
        pass

    counts = lock["record_count_per_source"]
    layers = lock["object_layer_per_source"]
    reg_by = {r["source_id"]: r for r in registry}

    # T01
    rows = []
    for sid in sorted(counts.keys()):
        r = reg_by.get(sid, {})
        rows.append(
            {
                "source_id": sid,
                "source_name": r.get("source_name", sid),
                "jurisdiction": r.get("jurisdiction", ""),
                "access_method": r.get("access_method", ""),
                "programme_level_unit": r.get("programme_level_unit", ""),
                "filter_applied": r.get("filter_applied", ""),
                "object_layer": layers.get(sid, ""),
                "record_count": str(counts[sid]),
                "collection_date": r.get("collection_date") or lock.get("collection_date", ""),
                "corpus_sha256": lock["sha256"],
            }
        )
    _write_triple(
        "T01_corpus_composition",
        "Corpus composition",
        "Composition of the locked multi-source public inventory corpus used for Disclosure Functions v1 schema analysis.",
        "tab:corpus_composition",
        list(rows[0].keys()),
        rows,
        f"Total records = {lock['total_record_count']}. Counts from corpus lock; registry metadata from source_registry_expanded.csv. Not a ranking.",
        "AUTO — methods/descriptive (frozen corpus + registry)",
        [
            "localgovbench_measurement_validation/affordance/locks/corpus_lock_v1.json",
            "localgovbench_measurement_validation/pilot_public_satisfiability/data/source_registry_expanded.csv",
        ],
    )

    # T02 object layers
    rows = [
        {
            "source_id": sid,
            "object_layer": layers[sid],
            "record_count": str(counts[sid]),
            "note": {
                "search_api_slim": "UK-ATRS object layer is search API slim, not full ATRS.",
                "case_catalogue": "EU-PSTW is a case catalogue contrast stratum.",
            }.get(layers[sid], ""),
        }
        for sid in sorted(layers)
    ]
    _write_triple(
        "T02_object_layers",
        "Schema object layers by source",
        "Schema object layer assigned to each inventory source in Disclosure Functions v1.",
        "tab:object_layers",
        list(rows[0].keys()),
        rows,
        "From corpus lock object_layer_per_source. Methods table only.",
        "AUTO — methods (corpus lock)",
        ["localgovbench_measurement_validation/affordance/locks/corpus_lock_v1.json"],
    )

    # T03 functions
    rows = []
    for f in functions.get("core_functions", []):
        rows.append(
            {
                "function_id": f["id"],
                "display_name": f.get("display_name", ""),
                "tier": "core",
                "status": f.get("status", ""),
                "applicability_default": f.get("applicability_default", ""),
                "primary_question": " ".join((f.get("primary_question") or "").split()),
            }
        )
    for f in functions.get("modules", []):
        rows.append(
            {
                "function_id": f["id"],
                "display_name": f.get("display_name", ""),
                "tier": "module",
                "status": f.get("status", ""),
                "applicability_default": f.get("applicability_default", ""),
                "primary_question": " ".join((f.get("primary_question") or "").split()),
            }
        )
    _write_triple(
        "T03_disclosure_functions_catalogue",
        "Disclosure Functions v1 catalogue",
        "Normative Disclosure Functions v1 catalogue (core functions and modules).",
        "tab:disclosure_functions",
        list(rows[0].keys()),
        rows,
        "Copied from disclosure_functions_v1.yaml. Definitions abbreviated to primary_question; full text in YAML/codebook.",
        "AUTO — methods (normative catalogue)",
        ["localgovbench_measurement_validation/affordance/config/disclosure_functions_v1.yaml"],
    )

    # T04 inventory summary
    by = Counter(r["source_name"] for r in inv)
    rows = []
    for sid in sorted(by):
        rows.append(
            {
                "source_name": sid,
                "object_layer": layers.get(sid, ""),
                "n_observed_fields": str(by[sid]),
                "schema_inventory_version": inv[0].get("schema_inventory_version", ""),
                "corpus_lock_reference": inv[0].get("corpus_lock_reference", ""),
            }
        )
    rows.append(
        {
            "source_name": "TOTAL",
            "object_layer": "",
            "n_observed_fields": str(len(inv)),
            "schema_inventory_version": inv[0].get("schema_inventory_version", ""),
            "corpus_lock_reference": inv[0].get("corpus_lock_reference", ""),
        }
    )
    _write_triple(
        "T04_schema_inventory_summary",
        "Observed schema inventory summary",
        "Counts of distinct observed raw fields per source in the frozen schema inventory.",
        "tab:schema_inventory_summary",
        list(rows[0].keys()),
        rows,
        "Field counts are observational inventory statistics, not disclosure-function support codes.",
        "AUTO — methods (schema inventory)",
        ["localgovbench_measurement_validation/affordance/outputs/schema_inventory_v1.csv"],
    )

    # T05 coding universe
    rows = [
        {
            "coding_unit_key": f"{r.get('source_name')}__{r.get('disclosure_function_id')}",
            "source_name": r.get("source_name", ""),
            "schema_object_id": r.get("schema_object_id", ""),
            "disclosure_function_id": r.get("disclosure_function_id", ""),
            "function_display_name": r.get("function_display_name", ""),
            "tier": r.get("tier", ""),
            "scoring_role": r.get("scoring_role", ""),
            "default_applicability": r.get("default_applicability", ""),
        }
        for r in template
    ]
    _write_triple(
        "T05_coding_unit_universe",
        "Full schema×function coding universe",
        "Full blank coding universe (schema object × disclosure function) for Disclosure Functions v1.",
        "tab:coding_universe",
        list(rows[0].keys()),
        rows,
        f"n = {len(rows)} (expected 55). Blank template only — no human judgments.",
        "AUTO — methods (coding template)",
        ["localgovbench_measurement_validation/affordance/coding/templates/schema_coding_template_v1.csv"],
    )

    # T06 pilot
    rows = [
        {
            "pilot_unit_id": r.get("pilot_unit_id", ""),
            "source_name": r.get("source_name", ""),
            "disclosure_function_id": r.get("disclosure_function_id", ""),
            "function_display_name": r.get("function_display_name", ""),
            "tier": r.get("tier", ""),
            "default_applicability": r.get("default_applicability", ""),
            "selection_rationale": r.get("selection_rationale", ""),
            "specification_version": r.get("specification_version", ""),
            "corpus_lock_reference": r.get("corpus_lock_reference", ""),
        }
        for r in pilot
    ]
    _write_triple(
        "T06_pilot_unit_selection",
        "Pilot coding unit selection",
        "Pilot subset of coding units selected for independent double-coding, with frozen selection rationales.",
        "tab:pilot_units",
        list(rows[0].keys()),
        rows,
        f"n = {len(rows)} (expected 33). Selection rationales are design metadata, not coder judgments.",
        "AUTO — methods (pilot manifest)",
        ["localgovbench_measurement_validation/affordance/coding/templates/pilot_coding_manifest_v1.csv"],
    )

    # T07 labels
    rows = []
    for dim, vals in labels.items():
        for v in vals:
            rows.append({"dimension": dim, "allowed_value": v, "specification_version": "1.0.0"})
    _write_triple(
        "T07_coding_label_enumerations",
        "Coding label enumerations",
        "Frozen human-coding enumerations for Disclosure Functions v1.",
        "tab:coding_labels",
        ["dimension", "allowed_value", "specification_version"],
        rows,
        "From coding_labels_v1.yaml (principal dimensions). Full file remains authoritative.",
        "AUTO — methods (coding labels)",
        ["localgovbench_measurement_validation/affordance/coding/config/coding_labels_v1.yaml"],
    )

    # T08 candidates summary (methods)
    cand = _read_csv(AFF / "config" / "field_function_candidates_v1.csv")
    # summarize counts by source×function×label if columns exist
    cols = list(cand[0].keys()) if cand else []
    key_src = "source_name" if "source_name" in cols else cols[0]
    key_fn = "disclosure_function_id" if "disclosure_function_id" in cols else (
        "function_id" if "function_id" in cols else cols[1]
    )
    key_lab = "mapping_label" if "mapping_label" in cols else (
        "label" if "label" in cols else None
    )
    counter: Counter[tuple[str, str, str]] = Counter()
    for r in cand:
        lab = r.get(key_lab, "") if key_lab else ""
        counter[(r.get(key_src, ""), r.get(key_fn, ""), lab)] += 1
    rows = [
        {
            "source_name": a,
            "disclosure_function_id": b,
            "mapping_label": c,
            "n_candidate_rows": str(n),
        }
        for (a, b, c), n in sorted(counter.items())
    ]
    if rows:
        _write_triple(
            "T08_field_function_candidate_summary",
            "Field–function candidate mapping summary",
            "Summary counts of frozen field–function candidate mapping rows by source, function, and mapping label.",
            "tab:field_function_candidates",
            list(rows[0].keys()),
            rows,
            "Candidates are specification inputs for coders, not final support decisions.",
            "AUTO — methods (candidate map)",
            ["localgovbench_measurement_validation/affordance/config/field_function_candidates_v1.csv"],
        )

    # Future Results placeholders — headers only
    future = [
        (
            "T09_schema_affordance_matrix",
            "Schema affordance matrix (post-coding)",
            "Schema disclosure affordance by source and disclosure function after human coding and adjudication.",
            "tab:affordance_matrix",
            [
                "source_name",
                "disclosure_function_id",
                "applicability_label",
                "support_level",
                "encoding_type",
                "documentary_linkage_layer",
                "adjudication_status",
            ],
            "Requires completed dual coding + adjudication + Phase 3 pipeline outputs. Do not invent cells.",
        ),
        (
            "T10_coder_disagreements",
            "Coder disagreements (pilot)",
            "Units with disagreement between independent coders prior to adjudication.",
            "tab:coder_disagreements",
            [
                "coding_unit_id",
                "source_name",
                "disclosure_function_id",
                "field_name",
                "coder_a_value",
                "coder_b_value",
            ],
            "Requires export_disagreements on completed pilot sheets.",
        ),
        (
            "T11_irr_summary",
            "Inter-rater reliability summary",
            "Agreement statistics for double-coded pilot units (coefficients per analysis plan).",
            "tab:irr_summary",
            ["label_dimension", "n_units", "coefficient", "coefficient_type", "notes"],
            "Requires completed coding + IRR computation per irr_analysis_plan_v1.md. Not computed in this generator.",
        ),
        (
            "T12_record_realization_rates",
            "Record-level realization rates",
            "Record-level realization of disclosure functions among applicable published records.",
            "tab:realization_rates",
            [
                "source_name",
                "disclosure_function_id",
                "n_records",
                "n_applicable",
                "n_realized",
                "realization_rate",
            ],
            "Future empirical stage. Phase 3 emits templates only; do not invent rates.",
        ),
        (
            "T13_affordance_realization_gap",
            "Affordance–realization gap",
            "Gap between schema affordance and record-level realization by source and function.",
            "tab:affordance_realization_gap",
            [
                "source_name",
                "disclosure_function_id",
                "support_level",
                "realization_rate",
                "gap_descriptor",
            ],
            "Future analysis stage after affordance coding and realization measurement.",
        ),
    ]
    for tid, title, caption, label, fields, notes in future:
        _write_triple(
            tid,
            title,
            caption,
            label,
            fields,
            [],
            notes,
            "PLACEHOLDER — requires future study inputs (not Results)",
            ["(pending completed coding / pipeline / realization stage)"],
        )


def _fig_script_header(fig_id: str) -> str:
    return textwrap.dedent(
        f'''\
        #!/usr/bin/env python3
        """Generate {fig_id} from repository artefacts. No invented findings."""
        from __future__ import annotations

        import json
        from pathlib import Path

        import matplotlib

        matplotlib.use("Agg")
        import matplotlib.pyplot as plt

        REPO = Path(__file__).resolve().parents[2]
        OUT = REPO / "paper_assets" / "figures" / "{fig_id}" / "{fig_id}.png"
        '''
    )


def generate_figures() -> None:
    # F01 corpus bars — runnable now
    script_f01 = _fig_script_header("F01_corpus_record_counts") + textwrap.dedent(
        """\
        def main() -> None:
            lock = json.loads(
                (
                    REPO
                    / "localgovbench_measurement_validation/affordance/locks/corpus_lock_v1.json"
                ).read_text(encoding="utf-8")
            )
            counts = lock["record_count_per_source"]
            sources = sorted(counts)
            values = [counts[s] for s in sources]
            fig, ax = plt.subplots(figsize=(8, 4.5))
            ax.bar(sources, values, color="#4C72B0")
            ax.set_ylabel("Records (n)")
            ax.set_title("Locked corpus record counts by source")
            ax.tick_params(axis="x", rotation=30)
            ax.set_ylim(0, max(values) * 1.15)
            for i, v in enumerate(values):
                ax.text(i, v, str(v), ha="center", va="bottom", fontsize=9)
            fig.tight_layout()
            OUT.parent.mkdir(parents=True, exist_ok=True)
            fig.savefig(OUT, dpi=300)
            print(OUT)

        if __name__ == "__main__":
            main()
        """
    )
    _write_figure_scaffold(
        "F01_corpus_record_counts",
        "Corpus record counts by source",
        "Record counts in the locked multi-source public inventory corpus (Disclosure Functions v1). Bars are descriptive corpus composition, not a ranking of jurisdictions.",
        "AUTO — generatable from corpus lock",
        ["localgovbench_measurement_validation/affordance/locks/corpus_lock_v1.json"],
        "paper_assets/figures/F01_corpus_record_counts/F01_corpus_record_counts.png",
        ["Supplement A", "T01_corpus_composition"],
        "make_F01_corpus_record_counts.py",
        script_f01,
    )

    script_f02 = _fig_script_header("F02_inventory_field_counts") + textwrap.dedent(
        """\
        import csv

        def main() -> None:
            path = (
                REPO
                / "localgovbench_measurement_validation/affordance/outputs/schema_inventory_v1.csv"
            )
            with path.open(encoding="utf-8", newline="") as handle:
                rows = list(csv.DictReader(handle))
            from collections import Counter

            counts = Counter(r["source_name"] for r in rows)
            sources = sorted(counts)
            values = [counts[s] for s in sources]
            fig, ax = plt.subplots(figsize=(8, 4.5))
            ax.bar(sources, values, color="#55A868")
            ax.set_ylabel("Distinct observed fields")
            ax.set_title("Observed schema inventory field counts by source")
            ax.tick_params(axis="x", rotation=30)
            fig.tight_layout()
            OUT.parent.mkdir(parents=True, exist_ok=True)
            fig.savefig(OUT, dpi=300)
            print(OUT)

        if __name__ == "__main__":
            main()
        """
    )
    _write_figure_scaffold(
        "F02_inventory_field_counts",
        "Observed schema field counts",
        "Number of distinct observed raw fields per source in the frozen schema inventory. These are observational inventory counts, not disclosure-function support codes.",
        "AUTO — generatable from schema inventory",
        ["localgovbench_measurement_validation/affordance/outputs/schema_inventory_v1.csv"],
        "paper_assets/figures/F02_inventory_field_counts/F02_inventory_field_counts.png",
        ["Supplement B", "T04_schema_inventory_summary"],
        "make_F02_inventory_field_counts.py",
        script_f02,
    )

    script_f03 = _fig_script_header("F03_disclosure_functions_tiers") + textwrap.dedent(
        """\
        import yaml

        def main() -> None:
            path = (
                REPO
                / "localgovbench_measurement_validation/affordance/config/disclosure_functions_v1.yaml"
            )
            data = yaml.safe_load(path.read_text(encoding="utf-8"))
            core = [f["id"] for f in data.get("core_functions", [])]
            mods = [f["id"] for f in data.get("modules", [])]
            fig, ax = plt.subplots(figsize=(8, 5))
            y = list(range(len(core + mods)))
            labels = core + mods
            colors = ["#4C72B0"] * len(core) + ["#DD8452"] * len(mods)
            ax.barh(y, [1] * len(labels), color=colors)
            ax.set_yticks(y)
            ax.set_yticklabels(labels, fontsize=9)
            ax.set_xticks([])
            ax.set_xlim(0, 1.5)
            ax.set_title("Disclosure Functions v1 (core vs module)")
            ax.invert_yaxis()
            fig.tight_layout()
            OUT.parent.mkdir(parents=True, exist_ok=True)
            fig.savefig(OUT, dpi=300)
            print(OUT)

        if __name__ == "__main__":
            main()
        """
    )
    _write_figure_scaffold(
        "F03_disclosure_functions_tiers",
        "Disclosure Functions v1 tier overview",
        "Overview of Disclosure Functions v1 identifiers by tier (core vs module). Definitional methods figure; not an empirical result.",
        "AUTO — generatable from function catalogue",
        ["localgovbench_measurement_validation/affordance/config/disclosure_functions_v1.yaml"],
        "paper_assets/figures/F03_disclosure_functions_tiers/F03_disclosure_functions_tiers.png",
        ["Supplement C", "T03_disclosure_functions_catalogue"],
        "make_F03_disclosure_functions_tiers.py",
        script_f03,
    )

    script_f04 = _fig_script_header("F04_coding_universe_grid") + textwrap.dedent(
        """\
        import csv
        import numpy as np

        def main() -> None:
            path = (
                REPO
                / "localgovbench_measurement_validation/affordance/coding/templates/schema_coding_template_v1.csv"
            )
            with path.open(encoding="utf-8", newline="") as handle:
                rows = list(csv.DictReader(handle))
            sources = sorted({r["source_name"] for r in rows})
            funcs = sorted({r["disclosure_function_id"] for r in rows})
            pilot_path = (
                REPO
                / "localgovbench_measurement_validation/affordance/coding/templates/pilot_coding_manifest_v1.csv"
            )
            with pilot_path.open(encoding="utf-8", newline="") as handle:
                pilot = {
                    (r["source_name"], r["disclosure_function_id"])
                    for r in csv.DictReader(handle)
                }
            grid = np.zeros((len(funcs), len(sources)))
            for i, f in enumerate(funcs):
                for j, s in enumerate(sources):
                    if (s, f) in {(r["source_name"], r["disclosure_function_id"]) for r in rows}:
                        grid[i, j] = 2 if (s, f) in pilot else 1
            fig, ax = plt.subplots(figsize=(8, 6))
            im = ax.imshow(grid, aspect="auto", cmap="Blues", vmin=0, vmax=2)
            ax.set_xticks(range(len(sources)))
            ax.set_xticklabels(sources, rotation=30, ha="right", fontsize=8)
            ax.set_yticks(range(len(funcs)))
            ax.set_yticklabels(funcs, fontsize=8)
            ax.set_title("Coding universe (1=full template; 2=pilot subset)")
            cbar = fig.colorbar(im, ax=ax, ticks=[0, 1, 2])
            cbar.ax.set_yticklabels(["absent", "template", "pilot"])
            fig.tight_layout()
            OUT.parent.mkdir(parents=True, exist_ok=True)
            fig.savefig(OUT, dpi=300)
            print(OUT)

        if __name__ == "__main__":
            main()
        """
    )
    _write_figure_scaffold(
        "F04_coding_universe_grid",
        "Coding universe and pilot subset",
        "Grid of schema-object × disclosure-function coding units in the full template, highlighting the pilot subset. Design/methods figure; contains no coder judgments.",
        "AUTO — generatable from coding templates",
        [
            "localgovbench_measurement_validation/affordance/coding/templates/schema_coding_template_v1.csv",
            "localgovbench_measurement_validation/affordance/coding/templates/pilot_coding_manifest_v1.csv",
        ],
        "paper_assets/figures/F04_coding_universe_grid/F04_coding_universe_grid.png",
        ["Supplement D", "T05_coding_unit_universe", "T06_pilot_unit_selection"],
        "make_F04_coding_universe_grid.py",
        script_f04,
    )

    # Future placeholders with stub scripts that exit explaining missing inputs
    for fig_id, title, caption, needed, xref in [
        (
            "F05_schema_affordance_heatmap",
            "Schema affordance heatmap",
            "Heatmap of adjudicated schema disclosure affordance (support level) by source and disclosure function. Requires completed coding and Phase 3 matrix export.",
            ["affordance/experiments/outputs/*_schema_affordance_matrix.csv (future)"],
            ["Supplement F", "T09_schema_affordance_matrix"],
        ),
        (
            "F06_coder_agreement",
            "Coder agreement overview",
            "Overview of independent-coder agreement and residual disagreements for the pilot. Requires completed dual coding and disagreement export.",
            ["pilot completed sheets + disagreements CSV (future)"],
            ["Supplement D", "T10_coder_disagreements", "T11_irr_summary"],
        ),
        (
            "F07_realization_rates",
            "Record-level realization rates",
            "Record-level realization rates by source and function among applicable records. Future empirical stage; not generated from placeholders.",
            ["realization analysis outputs (future)"],
            ["Supplement F", "T12_record_realization_rates"],
        ),
        (
            "F08_affordance_realization_gap",
            "Affordance–realization gap",
            "Comparison of schema affordance and record-level realization. Future analysis stage after both layers exist.",
            ["affordance matrix + realization rates (future)"],
            ["T09_schema_affordance_matrix", "T12_record_realization_rates", "T13_affordance_realization_gap"],
        ),
    ]:
        script = textwrap.dedent(
            f'''\
            #!/usr/bin/env python3
            """Stub for {fig_id}. Refuses to invent findings."""
            import sys
            print(
                "{fig_id}: required study inputs are not present. "
                "Do not invent results. Needed: {needed[0]}",
                file=sys.stderr,
            )
            sys.exit(2)
            '''
        )
        _write_figure_scaffold(
            fig_id,
            title,
            caption,
            "PLACEHOLDER — future empirical inputs required",
            needed,
            f"paper_assets/figures/{fig_id}/{fig_id}.png",
            xref,
            f"make_{fig_id}.py",
            script,
        )


def write_appendices_and_methods() -> None:
    app = ASSETS / "appendices"
    app.mkdir(parents=True, exist_ok=True)
    (app / "README.md").write_text(
        textwrap.dedent(
            """\
            # Appendices (manuscript packaging)

            These appendices **point to** authoritative repository artefacts and
            `docs/supplements/`. They do not duplicate normative catalogues in full.

            | Appendix | Content | Authoritative path |
            |----------|---------|-------------------|
            | A | Corpus lock | `docs/supplements/A_corpus.md` |
            | B | Schema inventory | `docs/supplements/B_observed_schema_inventory.md` |
            | C | Disclosure Functions v1 | `docs/supplements/C_disclosure_functions_v1.md` |
            | D | Coding framework | `docs/supplements/D_coding_framework.md` |
            | E | Validation rules | `docs/supplements/E_validation_rules.md` |
            | F | Experimental pipeline | `docs/supplements/F_experimental_pipeline.md` |
            | G | Reproducibility | `docs/supplements/G_reproducibility.md` |
            | H | Repository structure | `docs/supplements/H_repository_structure.md` |
            | I | Software citation | `docs/supplements/I_software_citation.md` |
            | J | Version history | `docs/supplements/J_version_history.md` |

            For journal submission, either attach `docs/supplements/*.md` or compile
            from those sources. Do not paste completed coding sheets into appendices
            unless ethics/data policy explicitly allows.
            """
        ),
        encoding="utf-8",
    )
    for letter, name in [
        ("A", "corpus"),
        ("B", "observed_schema_inventory"),
        ("C", "disclosure_functions_v1"),
        ("D", "coding_framework"),
        ("E", "validation_rules"),
        ("F", "experimental_pipeline"),
        ("G", "reproducibility"),
        ("H", "repository_structure"),
        ("I", "software_citation"),
        ("J", "version_history"),
    ]:
        (app / f"appendix_{letter}_{name}.md").write_text(
            f"# Appendix {letter} — {name.replace('_', ' ').title()}\n\n"
            f"See master supplement: [`docs/supplements/"
            f"{letter}_{name}.md`](../../docs/supplements/{letter}_{name}.md)\n\n"
            f"(Wrapper only; authoritative text remains in `docs/supplements/`.)\n",
            encoding="utf-8",
        )

    methods = ASSETS / "methods_assets"
    methods.mkdir(parents=True, exist_ok=True)
    (methods / "README.md").write_text(
        textwrap.dedent(
            """\
            # Methods assets index

            Pointers to frozen Methods ingredients for manuscript drafting.
            **No Results.**

            | Asset | Path |
            |-------|------|
            | Affordance package overview | `localgovbench_measurement_validation/affordance/README.md` |
            | Function catalogue | `.../affordance/config/disclosure_functions_v1.yaml` |
            | Codebook | `.../affordance/coding/config/codebook_affordance_v1.md` |
            | Coder instructions | `.../affordance/coding/config/coder_instructions_v1.md` |
            | Double-coding protocol | `.../affordance/coding/config/double_coding_protocol_v1.md` |
            | Adjudication protocol | `.../affordance/coding/adjudication/adjudication_protocol_v1.md` |
            | IRR plan (no coefficients) | `.../affordance/coding/config/irr_analysis_plan_v1.md` |
            | Experiment pipeline | `.../affordance/experiments/EXPERIMENT_PIPELINE.md` |
            | Pilot administration | `.../affordance/coding/pilot_round_01/administration/` |
            | Claims / non-claims (legacy shortfall draft — do not mix constructs) | `paper_data_policy/claims_and_nonclaims.md` |
            | Active non-claims | Root `README.md`, `CITATION.cff`, `docs/releases/public_positioning_v0.2.0.md` |

            ## Construct boundary

            Manuscript Methods for the **active** paper path must describe
            **schema disclosure affordance / Disclosure Functions v1**.
            Do not import shortfall/readiness tables from
            `pilot_public_satisfiability/outputs/` as DF Results.
            """
        ),
        encoding="utf-8",
    )
    # Snapshot key path list
    (methods / "frozen_path_checklist.md").write_text(
        textwrap.dedent(
            """\
            # Frozen path checklist (Methods)

            - [ ] Corpus SHA-256 matches `affordance/locks/corpus_lock_v1.json`
            - [ ] Inventory `corpus_lock_reference` matches lock SHA
            - [ ] Function catalogue version 1.0.0
            - [ ] Coding labels version 1.0.0
            - [ ] Template has 55 units; pilot manifest 33 units
            - [ ] Blank pilot packets have empty judgment fields
            - [ ] Software citation DOI 10.5281/zenodo.21500899 (active)
            """
        ),
        encoding="utf-8",
    )


def write_latex_bundle() -> None:
    latex = ASSETS / "latex"
    (latex / "tables").mkdir(parents=True, exist_ok=True)
    (latex / "figures").mkdir(parents=True, exist_ok=True)
    (latex / "README.md").write_text(
        textwrap.dedent(
            """\
            # LaTeX inclusion helpers

            ## Tables

            Auto-copied `.tex` fragments live in `latex/tables/`.
            Requires `booktabs` in the manuscript preamble.

            Example:

            ```latex
            \\input{../localgovbench/paper_assets/latex/tables/T01_corpus_composition.tex}
            ```

            Adjust the relative path to your manuscript tree.

            ## Figures

            After running figure scripts, include PNGs, e.g.:

            ```latex
            \\includegraphics[width=\\linewidth]{../localgovbench/paper_assets/figures/F01_corpus_record_counts/F01_corpus_record_counts.png}
            ```

            Use captions from each figure's `caption.md`.
            """
        ),
        encoding="utf-8",
    )
    # figure include stubs
    for fig_dir in sorted((ASSETS / "figures").glob("F*")):
        fig_id = fig_dir.name
        stub = textwrap.dedent(
            f"""\
            % Placeholder include for {fig_id}
            % Replace path after running paper_assets/scripts/make_{fig_id}.py
            \\begin{{figure}}[t]
            \\centering
            \\includegraphics[width=\\linewidth]{{paper_assets/figures/{fig_id}/{fig_id}.png}}
            \\caption{{See paper\\_assets/figures/{fig_id}/caption.md}}
            \\label{{fig:{fig_id.lower()}}}
            \\end{{figure}}
            """
        )
        (latex / "figures" / f"{fig_id}.tex").write_text(stub, encoding="utf-8")


def write_manifest() -> None:
    manifest = ASSETS / "paper_asset_manifest.md"
    manifest.write_text(
        textwrap.dedent(
            """\
            # Paper asset manifest

            **Construct:** Disclosure Functions v1 / schema disclosure affordance  
            **Generator:** `paper_assets/scripts/generate_all_paper_assets.py`  
            **Rule:** Do **not** invent Results. Placeholders stay empty until real inputs exist.

            ## Dependencies

            | Dependency | Role |
            |------------|------|
            | Python ≥ 3.11 | Generator + figure scripts |
            | PyYAML | Function catalogue |
            | matplotlib | Figure scripts F01–F04 |
            | Frozen corpus lock + inventory | Methods tables/figures |
            | Source registry CSV | Corpus metadata columns |
            | Coding templates / pilot manifest | Unit design tables/figures |
            | Completed human coding (future) | T09–T11, F05–F06 |
            | Realization stage outputs (future) | T12–T13, F07–F08 |

            Install (from repo root):

            ```bash
            pip install -e ".[dev]"
            ```

            ## Generation order

            1. Ensure Phase 1–2 freezes exist (`affordance/locks`, `outputs`, `coding/templates`).  
            2. Run:

               ```bash
               python3.12 paper_assets/scripts/generate_all_paper_assets.py
               ```

            3. Generate auto figures:

               ```bash
               python3.12 paper_assets/scripts/make_F01_corpus_record_counts.py
               python3.12 paper_assets/scripts/make_F02_inventory_field_counts.py
               python3.12 paper_assets/scripts/make_F03_disclosure_functions_tiers.py
               python3.12 paper_assets/scripts/make_F04_coding_universe_grid.py
               ```

            4. Leave F05–F08 / T09–T13 placeholders until study inputs exist.  
            5. Do **not** run legacy shortfall figure pipelines as DF Results.

            ## Files generated automatically (methods / descriptive)

            ### Tables (CSV + Markdown + LaTeX)

            | ID | Content |
            |----|---------|
            | T01 | Corpus composition |
            | T02 | Object layers |
            | T03 | Disclosure Functions catalogue |
            | T04 | Schema inventory summary |
            | T05 | Full coding universe (55) |
            | T06 | Pilot unit selection (33) |
            | T07 | Coding label enumerations |
            | T08 | Field–function candidate summary |

            ### Figures (scripts + placeholders; PNG when scripts succeed)

            | ID | Content |
            |----|---------|
            | F01 | Corpus record counts |
            | F02 | Inventory field counts |
            | F03 | Function tier overview |
            | F04 | Coding universe / pilot grid |

            ### Other

            - `appendices/` wrappers → `docs/supplements/`  
            - `methods_assets/` checklists  
            - `latex/tables/*.tex`, `latex/figures/*.tex` include stubs  

            ## Files requiring future inputs (manual / empirical interpretation)

            | ID | Required future input | Manual interpretation? |
            |----|----------------------|-------------------------|
            | T09 schema affordance matrix | Completed coding + adjudication + Phase 3 matrix | Yes — Methods/Results framing of support levels |
            | T10 coder disagreements | Dual completed sheets + disagreement export | Yes — qualitative disagreement themes optional |
            | T11 IRR summary | IRR computation per plan | Yes — coefficient choice/reporting |
            | T12 realization rates | Future realization measurement | Yes |
            | T13 affordance–realization gap | T09 + T12 | Yes |
            | F05–F08 | Same as related tables | Yes |

            ## Required future inputs (checklist)

            - [ ] `pilot_round_01_coder_A_completed.csv` / `_B_completed.csv` (human)  
            - [ ] Disagreement export + adjudication completed sheet  
            - [ ] Phase 3 affordance matrix for cited `experiment_id`  
            - [ ] IRR statistics computed per `irr_analysis_plan_v1.md`  
            - [ ] Realization inputs filled (not templates alone)  
            - [ ] Gap analysis notebook/script (not yet a DF Results claim)

            ## Explicitly out of scope for this asset pack

            Legacy public-satisfiability / shortfall outputs under
            `pilot_public_satisfiability/outputs/` and `figures/` are **not**
            copied into `paper_assets/` as Disclosure Functions Results.
            They belong to a different construct (v0.1 ceiling/shortfall pilot).

            ## Cross references

            - Supplements A–J: `docs/supplements/`  
            - Affordance package: `localgovbench_measurement_validation/affordance/`  
            - Software citation: `CITATION.cff` / Supplement I  
            """
        ),
        encoding="utf-8",
    )


def write_readme() -> None:
    (ASSETS / "README.md").write_text(
        textwrap.dedent(
            """\
            # Paper assets (Disclosure Functions v1)

            Reproducible manuscript ingredients generated from repository artefacts.

            **Does not write Results. Does not invent findings.**

            ```
            paper_assets/
              paper_asset_manifest.md
              tables/           # T01–T13 (CSV + MD + TeX)
              figures/          # F01–F08 (caption, placeholder, script, meta)
              appendices/       # wrappers to docs/supplements
              methods_assets/   # Methods drafting pointers
              latex/            # collected includes
              scripts/          # generators
            ```

            ```bash
            python3.12 paper_assets/scripts/generate_all_paper_assets.py
            python3.12 paper_assets/scripts/make_F01_corpus_record_counts.py
            python3.12 paper_assets/scripts/make_F02_inventory_field_counts.py
            python3.12 paper_assets/scripts/make_F03_disclosure_functions_tiers.py
            python3.12 paper_assets/scripts/make_F04_coding_universe_grid.py
            ```

            See `paper_asset_manifest.md` for generation order and future inputs.
            """
        ),
        encoding="utf-8",
    )


def main() -> None:
    ASSETS.mkdir(parents=True, exist_ok=True)
    (ASSETS / "scripts").mkdir(parents=True, exist_ok=True)
    (ASSETS / "latex" / "tables").mkdir(parents=True, exist_ok=True)
    (ASSETS / "latex" / "figures").mkdir(parents=True, exist_ok=True)
    generate_tables()
    generate_figures()
    write_appendices_and_methods()
    write_latex_bundle()
    write_manifest()
    write_readme()
    # copy this generator into scripts if running from elsewhere — already located there when saved
    print(f"Wrote paper assets under {ASSETS}")


if __name__ == "__main__":
    main()
